import type { NextPage } from 'next';
import Head from 'next/head';
import Hero from '../components/hero';
import HomeNav from '../components/homeNav';
import { client } from '../utils/client';

const Home: NextPage = ({ content }: any) => {
  return (
    <div>
      <Head>
        <title>Snowboard Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-screen'>
        <HomeNav />
        <Hero content={content.hero} />
      </div>

      {/*  <main>
        <h2>New app here ✈️</h2>
      </main> */}
    </div>
  );
};

Home.defaultProps = {
  content: {
    features: [{ title: 'default feature', body: 'default body' }],
    hero: { title: 'RUN OVER EVERYTHING!', body: 'default body' },
  },
};

export default Home;
